sudo: false
language: node_js
node_js:
  - "8"
  - "9"
  
os:
  - osx

before_install:
  - npm set progress=false
  - mkdir -p "~/Library/Application Support/com.bohemiancoding.sketch3"
  - mkdir -p "~/Library/Application Support/com.bohemiancoding.sketch3/Plugins"

script:
  - npm install -g skpm
  - skpm create sketch-plugin-typescript --template=romansp/skpm-typescript
